#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer --url-ignore "/snars.org\/repeaters\/info/,/powerequipment\.honda\.com/,/ncpa\.n0ary\.org/" ./_site --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-architect.gemspec
