#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer --url-ignore "/snars.org\/repeaters\/info/,/powerequipment\.honda\.com/,/ncpa\.n0ary\.org/,/www\.hti\.umich\.edu/,/www\.sk3bg\.se/,/ww1x\.radio/" ./_site --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-architect.gemspec
